products/urls.py
from django.urls import path

from products.views import ProductsView, add_basket, remove_basket

app_name = 'products'

urlpatterns = [
    path('', ProductsView.as_view(), name='products'),

    path('category/<int:category_id>/', ProductsView.as_view(),
         name='cat_filter'),

    path('page/<int:page>/', ProductsView.as_view(), name='paginator'),
    path('basket/add/<int:product_id>/', add_basket, name='add_basket'),

    path('basket/delete/<int:product_id>/', remove_basket,
         name='remove_basket'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from store.views import IndexView
from orders.views import order_webhook

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='main'),
    path('stripe/webhook/', order_webhook, name='order_webhook'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('order/', include('orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

products/models.py
from django.db import models

import stripe
from django.conf import settings

from users.models import User


stripe.api_key = settings.STRIPE_SECRET_KEY


class ProductCategory(models.Model):

    name = models.CharField(max_length=30)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Product(models.Model):

    name = models.CharField(max_length=150)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images')
    stripe_product_price_id = models.CharField(
        max_length=128, null=True, blank=True,
    )
    category = models.ForeignKey(
        to=ProductCategory, on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

    def save(self,
             force_insert=False,
             force_update=False,
             using=None,
             update_fields=None,
             ):

        if not self.stripe_product_price_id:
            product_price = self.create_stripe_product_and_price()
            self.stripe_product_price_id = product_price['id']

        super().save(force_insert=False,
                     force_update=False,
                     using=None,
                     update_fields=None,
                     )

    def create_stripe_product_and_price(self):

        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'],
            unit_amount=round(self.price * 100),
            currency='rub',
        )

        return stripe_product_price


class BasketRelatedManager(models.QuerySet):

    def total_price(self):

        return sum(good.sum_price() for good in self)

    def total_quantity(self):

        return sum(good.quantity for good in self)


class Basket(models.Model):

    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=1)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketRelatedManager.as_manager()

    def __str__(self):

        return f'Корзина пользователя {self.user.get_full_name()}'

    def sum_price(self):

        return self.product.price * self.quantity

products/views.py
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.http import HttpResponseRedirect
from django.views.generic import ListView

from products.models import Basket, Product, ProductCategory

PER_PAGE = 3


class ProductsView(ListView):

    model = Product
    context_object_name = 'products'
    template_name = 'products/products.html'
    paginate_by = 3

    def get_queryset(self):
        """Filtration by category. If category_id is not None, return list
         goods filtered by category"""

        query_set = super().get_queryset()
        category_id = self.kwargs.get('category_id')

        return query_set.filter(category_id=category_id) if category_id \
            else query_set

    def get_context_data(self, *, object_list=None, **kwargs):

        context = super().get_context_data()
        categories = cache.get('categories')

        if not categories:
            context['categories'] = ProductCategory.objects.all()
            cache.set('categories', context['categories'], 30)

        else:
            context['categories'] = categories

        context['title'] = 'Catalog'
        return context


@login_required(redirect_field_name=None)
def add_basket(request, product_id):

    product = Product.objects.get(id=product_id)
    good_in_basket = Basket.objects.filter(user=request.user, product=product)

    if good_in_basket.exists():
        good = good_in_basket.first()
        good.quantity += 1
        good.save()

    else:
        Basket.objects.create(user=request.user, product=product)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required(redirect_field_name=None)
def remove_basket(request, product_id):

    product = Product.objects.get(id=product_id)
    Basket.objects.filter(user=request.user, product=product).delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

templates/products/products.html
{% extends 'base.html' %}
{% load humanize %}

{% load static cache %}

{% block title %} {{ title }} {% endblock %}

{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Store</h1>
            <div class="list-group">
            <a href="{% url 'products:products' %}" class="list-group-item">Все</a>
                {% for category in categories %}
                <a href="{% url 'products:cat_filter' category.id %}" class="list-group-item">{{ category.name }}</a>
                {% endfor %}
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            {% include 'components/carousel.html' %}

        {% cache 30 products %}
            <div class="row">
                {% for product in products %}
                <div class="col-lg-4 col-md-6 mb-4">

                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src="{{ product.image.url }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{ product.name }}</a>
                            </h4>

                            <h5>{{ product.price|intcomma }}</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a href="{% url 'products:add_basket' product.id %}" class="btn btn-outline-success">Отправить в корзину</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endcache %}

            {% include 'components/pagination.html' %}

        </div>

    </div>

</div>
{% endblock %}

{% block footer %}
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Store 2022</p>
    </div>
    <!-- /.container -->
</footer>
{% endblock %}