orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.CreateOrderView.as_view(), name='create_order'),

    path('success/', views.SuccessPaymentView.as_view(),
         name='payment_success'),

    path('cancel/', views.CancelPaymentView.as_view(), name='payment_cancel'),
]

products/urls.py
from django.urls import path

from products.views import ProductsView, add_basket, remove_basket

app_name = 'products'

urlpatterns = [
    path('', ProductsView.as_view(), name='products'),

    path('category/<int:category_id>/', ProductsView.as_view(),
         name='cat_filter'),

    path('page/<int:page>/', ProductsView.as_view(), name='paginator'),
    path('basket/add/<int:product_id>/', add_basket, name='add_basket'),

    path('basket/delete/<int:product_id>/', remove_basket,
         name='remove_basket'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from store.views import IndexView
from orders.views import order_webhook

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='main'),
    path('stripe/webhook/', order_webhook, name='order_webhook'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('order/', include('orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

templates/components/basket.html
{% load humanize %}

{% if basket %}
<h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
    Корзина <span class="badge badge-secondary badge-pill">{{ basket.total_quantity }}</span>
</h4>
    {% for good in basket %}
<div class="card mb-3">
    <div class="card-body">

        <h5 class="card-title">{{ good.product.name }}</h5>
        <p class="card-text">{{ good.product.description }}</p>

    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item bg-light">
            <div class="row text-center">
                <div class="col-lg-4">
                    <input name="basketID" type="number" class="form-control"
                           value="{{ good.quantity }}" min="0">
                </div>
                <div class="col-lg-4">{{ good.sum_price|intcomma }}</div>
                <div class="col-lg-4">
                    <a href="{% url 'products:remove_basket' good.product.id %}">
                        <i class="fas fa-trash"></i>
                    </a>
                </div>
            </div>
        </li>
    </ul>
</div>
    {% endfor %}
<div class="card mb-3">
    <div class="card-footer">
        <p class="float-left">Итого</p>
        <h4 class="float-right">{{ basket.total_price }} руб.</h4>
    </div>
</div>
<a class="btn btn-success btn-lg float-right" href="{% url 'orders:create_order' %}">
    Оформить заказ
</a>
{% else %}
<h4 class="mt-3 mb-3 text-center mb-3">
    Корзина пуста
</h4>
{% endif %}

templates/components/carousel.html
{% load static %}

<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">

        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
                <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>

</div>

templates/components/pagination.html
{% if is_paginated %}
<nav aria-label="Page navigation example">

        <ul class="pagination justify-content-center">
            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                <a class="page-link" href="
                {% if page_obj.has_previous %} {% url 'products:paginator' page_obj.previous_page_number %} {% else %} #{% endif %}"
                   tabindex="-1" aria-disabled="true">Предыдущая</a>
            </li>
            {% for page in paginator.page_range %}
                <li class="page-item"><a class="page-link" href="{% url 'products:paginator' page %}">{{ page }}</a></li>
            {% endfor %}
            <li class="page-item{% if not page_obj.has_next %} disabled {% endif %}">
                <a class="page-link" href="{% if page_obj.has_next %} {% url 'products:paginator' page_obj.next_page_number %} {% endif %}">
                    Следующая</a>
            </li>
        </ul>
</nav>
{% endif %}